import { type NextPage } from "next";
import Head from "next/head";
import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { api } from "~/utils/api";
import { type RouterOutputs } from "~/utils/api";
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
import Image from "next/image";
import { LoadingPage } from "~/components/loading";

dayjs.extend(relativeTime);

const CreatePostWizard = () => {
  const { user } = useUser();
  if (!user) return null;
  return (
    <div className="flex w-full gap-3">
      <Image
        src={user.profileImageUrl}
        alt="Profile Picture"
        width={56}
        height={56}
        className="h-16 w-16 rounded-full"
      />
      <input
        placeholder="Share your thoughts..."
        className="grow bg-transparent outline-none"
      />
    </div>
  );
};
type PostWithUser = RouterOutputs["posts"]["getAll"][number];
const PostView = (props: PostWithUser) => {
  const { post, author } = props;
  return (
    <div
      key={post.id}
      className="flex items-center gap-3 border-b border-slate-400 p-4"
    >
      <Image
        src={author.profileImageUrl}
        alt="profile picture"
        width={56}
        height={56}
        className="h-16 w-16 rounded-full"
      />
      <div className="flex flex-col">
        <div className="flex text-slate-300 gap-2">
          <span> {`@${author.username}`} </span>
          <span className=""> {`. ${dayjs(post.createdAt).fromNow()}`} </span>
        </div>
        <span> {post.content} </span>
      </div>
    </div>
  );
};

const Feed = () => {
  const { data, isLoading: postsLoading } = api.posts.getAll.useQuery();
  if (!postsLoading) return <LoadingPage />
  if (!data) return <div>Something went wrong</div>

  return (
    <div className="flex flex-col">
      {data.map((fullPost) => (
        <PostView {...fullPost} key={fullPost.post.id} />
      ))}
    </div>
    
}

const Home: NextPage = () => {
  const {user, isLoaded: userLoaded} = useUser();
 api.posts.getAll.useQuery();

  if (!userLoaded) return <div />;
  return (
    <>
      <Head>
        <title>ecomm solutions</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="h-full w-full border-x border-slate-400 md:max-w-2xl">
          {!user.isSignedIn && <SignInButton />}
          {user.isSignedIn && (
            <div>
              <div className="flex w-full gap-3 border-b border-slate-400 p-4">
                <CreatePostWizard />
                <SignOutButton />
              </div>
              
            </div>
          )}
        </div>
      </main>
    </>
  );
};

export default Home;
